# Generated by Django 5.2.5 on 2025-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_userproductreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation_cluster',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
