# Generated by Django 5.2.5 on 2025-08-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_useraddress_address_type_and_more'),
        ('shopping', '0003_product_recommendation_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_to_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraddress'),
        ),
    ]
