# Generated by Django 5.2.5 on 2025-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_order_address_to_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_to_deliver',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
