# Generated by Django 5.2.5 on 2025-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='UserAddress',
        ),
    ]
